### ISSUE TITLE
Back-end

### ISSUE THREAD

**Issue by MariaAbritta** [fga-eps-mds/2022-1-Squad4#2]
⚙️ Capacitação ⚙️
   * O mais importante não é ver todos os links e sim entenderem e trazerem dúvidas para serem sanadas, somos um time! 

Se capacitar em GitHub:
   - [x] Maria Abritta
   - [x] Leo
   - [x] Lucas
   - [x] Josué

Se capacitar em Node 1º etapa
   - [x] Maria Abritta
   - [ ] Leo
   - [ ] Lucas
   - [x] Josué

Se capacitar no Desafio 1
   - [x] Maria Abritta
   - [ ] Leo
   - [ ] Lucas
   - [x] Josué

Se capacitar em Node 2ª etapa
   - [x] Maria Abritta
   - [ ] Leo
   - [x] Lucas
   - [x] Josué

Se capacitar em Insomnia
   - [x] Maria Abritta
   - [ ] Leo
   - [x] Lucas
   - [ ] Josué

Link: https://docs.google.com/document/d/1vA5NcqEOCc9AEIhzRriz0d08efZs7WTOLa_2njNB4Gw/edit

**Comment by lucasgcaldas** [comment]
# RESTful API 

1. [What is a RESTful API? | Creating a REST API with Node.js](https://www.youtube.com/watch?v=0oXYLzuucwE&list=PL55RiY5tL51q4D-B63KBnygU6opNPFk_q&index=1&t=3s&ab_channel=Academind)
2. [O Que é uma API RESTful e Porque Isso Importa](https://www.hostinger.com.br/tutoriais/api-restful)

# Consumir API
Em node.js há diversas formas de se consumir APIs, as formas mais usadas que ja vi no mercado são essas duas:
1. [Axios](https://www.youtube.com/watch?v=XEq66Q4qQkw)
3. [Request](https://www.thepolyglotdeveloper.com/2017/10/consume-remote-api-data-nodejs-application/)

# Criar API 

[Essa](https://www.youtube.com/playlist?list=PL55RiY5tL51q4D-B63KBnygU6opNPFk_q) playlist é extensa (14 vídeos), ensina a fazer muitas coisas, porém pode servir de referência para quando formos criar a nossa.

No [meu repositório](https://github.com/lucasgcaldas/node-rest-shop) pessoal, tem a estrutura completa de como criar uma API dessa playlist acima, na época fui fazendo junto para aprender.

**Comment by lucasgcaldas** [comment]
@MariaAbritta no caso do Insomnia, creio que podemos usar o software que temos mais afinidade, não precisa ser esse em específico. Tem gente que usa o Postman ou qualquer outro, e por ai vai.
