### ISSUE TITLE
Time todo

### ISSUE THREAD

**Issue by MariaAbritta** [fga-eps-mds/2022-1-Squad4#3]
🫂 O TIME TODOOO 🫂
* O mais importante não é ver todos os links e sim entenderem e trazerem dúvidas para serem sanadas, somos um time! 

Se capacitar em Arquitetura
   - [x]  Amanda
   - [x] Luciano
   - [x] Lucas Gomes
   - [x] Antônio
   - [x] Maria Abritta
   - [x] Leo
   - [x] Lucas
   - [x] Josué
Link: https://drive.google.com/file/d/1w0CMAgZVZdZIA1uZ8LSdCYCDkf-zi05M/view?usp=sharing

**Comment by luciano-freitas-melo** [comment]
Oi pessoal!
Sobre a arquitetura, em OO eu utilizei o modelo MVC(Modelo, Visão e Controlador) no meu projeto (quem pegou OO com a Fabiana tá ligado nessa arquitetura). E ela é bem interessante de dar uma olhada, pq é algo de fácil entendimento e que consegue encapsular o código de um jeito bem legal.
Achei esse link aqui: https://martinfowler.com/bliki/PresentationDomainDataLayering.html , que fala sobre essa arquitetura. (Está em Inglês, então quem não estiver conseguindo entender é só me mandar um toque que eu explico :smiley: !

**Comment by amanda-noda** [comment]
Outro trabalho também, bem legal que tem uma arquitetura bem estruturada é esse aqui https://github.com/UnBArqDsw2020-2/2020.2_G5_EasyCoffee
Um projeto de outros alunos da UNB, inclusive achei a Api deles muito legal.
